version: "3"

services:
  nginx:
    image: chaberb/nginx-ssl
    depends_on:
      - web
      - pdf
    ports:
      - "443:443"
    volumes:
      - ./nginx-uwsgi.conf:/etc/nginx/nginx.conf

  web:
    build: flask_web
    links:
      - web_db
    volumes:
      - ./flask_web/app:/var/www/app

  pdf:
    build: flask_pdf
    links:
      - pdf_db
    volumes:
      - ./flask_pdf/app:/var/pdf/app

  web_db:
    image: redis

  pdf_db:
    image: redis
